<?php

/**
 * @file
 * Contains config_quickedit.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function config_quickedit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the config_quickedit module.
    case 'help.page.config_quickedit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_view_alter().
 */
function config_quickedit_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if ($entity instanceof \Drupal\Core\Entity\ContentEntityInterface) {
    /** @var \Drupal\config_quickedit\ViewAlter $viewAlter */
    $viewAlter = \Drupal::service('config_quickedit.view_alter');
    $viewAlter->addLinks($build, $entity);
  }

}

/**
 * Implements hook_preprocess().
 */
function config_quickedit_preprocess(&$variables, $hook) {
  if ($hook == 'field') {
    /** @var \Drupal\config_quickedit\ViewAlter $viewAlter */
    $viewAlter = \Drupal::service('config_quickedit.view_alter');
    $viewAlter->addFieldLinks($variables);
  }

}

/**
 * Implements hook_preprocess_HOOK() for field templates.
 */
function config_quickedit_preprocess_field(&$variables, $hook) {
  return;
  $element = &$variables['element'];
  if (isset($element['#contextual_links'])) {
    $variables['title_suffix']['contextual_links'] = array(
      '#type' => 'contextual_links_placeholder',
      '#id' => _contextual_links_to_id($element['#contextual_links']),
    );
    if (isset($variables['title_suffix']['contextual_links'])) {

      $element['#markup'] = SafeMarkup::format('<div@attributes></div>', ['@attributes' => new Attribute(['data-contextual-id' => $element['#id']])]);

    }
  }

}


function config_quickedit_contextual_links_view_alter(&$element, $items) {
  // Add another class to all contextual link lists to facilitate custom
  // styling.
  if (isset($element['#contextual_links']['config_quickedit'])) {
    // Add attributes to load correct form.
    foreach ($element['#links'] as $id => &$link) {
      // @todo Better way to identify links.
      if (stripos($id, 'config-quickedit') === 0) {
        /** @var \Drupal\Core\Url $url */
        $url = $link['url'];
        $attributes = [
          'data-config-quick-edit-parameters' => json_encode($url->getRouteParameters()),
          // @todo Convert into key to determine which config form to load.
          'data-config-quick-edit-route' => $url->getRouteName(),
         // 'class' => ['use-ajax'],
          //'data-dialog-type' => 'modal',
        ];
        $url->setOption('attributes', $attributes);
      }
    }
  }
}


function config_quickedit_toolbar() {
  $items = array();
  // A tray may be associated with a tab.
  //
  // When the tab is activated, the tray will become visible, either in a
  // horizontal or vertical orientation on the screen.
  //
  // The tray should contain a renderable array. An optional #heading property
  // can be passed. This text is written to a heading tag in the tray as a
  // landmark for accessibility.
  $items['config_quickedit'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'html_tag',
      '#tag' => 'a',
      '#value' => t('Config Quick Edit'),
    ),
    'tray' => array(
      '#heading' => t('Shopping cart actions'),
      'content' => [
        '#theme' => 'config_quickedit',
      ],
    ),
    '#weight' => 150,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function config_quickedit_theme() {
  return [
    'config_quickedit' => [
      'variables' => [
        'inner' => 'Dodo Brown',
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 */
function config_quickedit_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['entity_view_display']->setFormClass('config_quickedit_full','\Drupal\config_quickedit\Form\MinimalEntityViewDisplayForm');
  $entity_types['entity_view_display']->setFormClass('config_quickedit_formatter','\Drupal\config_quickedit\Form\FieldFormatter');
}
