# List all fields for EntityViewDisplay
config_quickedit.entity_view_fields:
  path: 'config_quickedit/entity-view-fields/{entity_type_id}/{bundle}/{view_mode_name}'
  defaults:
    _controller: '\Drupal\config_quickedit\Controller\FieldController::listField'
    _title: 'Fields'
  requirements:
    _custom_access: '\Drupal\config_quickedit\AccessChecker::checkEntityViewDisplay'
# Edit an individual field
config_quickedit.field_formatter:
  path: 'config_quickedit/field-formatter/{entity_type_id}/{bundle}/{view_mode_name}/{field_name}'
  defaults:
    _entity_form: entity_view_display.config_quickedit_formatter
    _title: 'Fields'
  requirements:
    _custom_access: '\Drupal\config_quickedit\AccessChecker::checkEntityViewDisplay'
